# Generated by Django 5.0.7 on 2024-07-16 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tempat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("deskripsi", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                (
                    "id_tempat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jadwal.tempat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fasilitas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objek_retribusi", models.CharField(max_length=255)),
                ("rincian", models.TextField()),
                ("keterangan", models.TextField()),
                (
                    "id_tempat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jadwal.tempat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("tanggal_mulai", models.DateTimeField()),
                ("tanggal_selesai", models.DateTimeField()),
                ("deskripsi", models.TextField()),
                (
                    "id_tempat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jadwal.tempat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                (
                    "id_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jadwal.role"
                    ),
                ),
            ],
        ),
    ]
