# Generated by Django 5.0.7 on 2024-07-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jadwal", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[("disetujui", "Disetujui"), ("diproses", "Diproses")],
                default="diproses",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tempat",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="foto_tempat/"),
        ),
    ]
