# Generated by Django 5.0.7 on 2024-07-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jadwal", "0003_event_status_tempat_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("disetujui", "Disetujui"),
                    ("diproses", "Diproses"),
                    ("ditolak", "Ditolak"),
                ],
                default="diproses",
                max_length=10,
            ),
        ),
    ]
