# Generated by Django 5.0.7 on 2024-08-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jadwal", "0006_alter_event_kategori_jadwal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="kategori_jadwal",
            field=models.CharField(
                choices=[("rutin", "Rutin"), ("tidak_rutin", "Tidak Rutin")],
                default="tidak_rutin",
                max_length=20,
            ),
        ),
    ]
