# Generated by Django 5.0.7 on 2024-08-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jadwal", "0007_alter_event_kategori_jadwal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="kategori_jadwal",
            field=models.CharField(
                choices=[("Rutin", "Rutin"), ("Tidak Rutin", "Tidak Rutin")],
                default="Tidak Rutin",
                max_length=20,
            ),
        ),
    ]
