# Generated by Django 5.0.7 on 2024-08-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jadwal", "0008_alter_event_kategori_jadwal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("Disetujui", "Disetujui"),
                    ("Diproses", "Diproses"),
                    ("Ditolak", "Ditolak"),
                ],
                default="diproses",
                max_length=10,
            ),
        ),
    ]
